spring.application.name=bolgManagement

#Port configuration
server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_managment
spring.datasource.username=postgres
spring.datasource.password=kitcoek
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=uday
spring.security.user.password=pass